#!/bin/sh

# pipe stderr to stdout and run crond
exec 2>&1

if [ "${RUN_CRON_TASKS:-true}" = "false" ]; then
  echo "RUN_CRON_TASKS is set to false, skipping cron job."
  # exit runit service by calling finish
  # https://smarden.org/runit/runsv.8.html
  exit 0
fi

exec /usr/sbin/crond -f
