#!/bin/sh
set -eu

# --- Functions ---

check_db_availability() {
    local db_host="$1"
    local db_port="$2"
    echo "Waiting for $db_host:$db_port to be ready..."
    while ! nc -w 1 "$db_host" "$db_port" >/dev/null 2>&1; do
        echo -n '.'
        sleep 1
    done
    echo "\nDatabase $db_host:$db_port is ready."
}

create_folders() {
    echo "Creating necessary folders..."

    # Create Dinamic folder if it doesn't exist
    [ ! -d "/var/www/html/Dinamic" ] && mkdir -p /var/www/html/Dinamic

    # Ensure MyFiles and Plugins folders exist
    [ ! -d "/var/www/html/volume/MyFiles" ] && mkdir -p /var/www/html/volume/MyFiles
    [ ! -d "/var/www/html/volume/Plugins" ] && mkdir -p /var/www/html/volume/Plugins

    # Set permissions
    chown -R nobody:nobody /var/www/html/Dinamic
    chown -R nobody:nobody /var/www/html/volume

    echo "Folders created successfully."
}

configure_htaccess() {
    echo "Configuring .htaccess..."

    if [ -f "/var/www/html/htaccess-sample" ] && [ ! -f "/var/www/html/.htaccess" ]; then
        cp /var/www/html/htaccess-sample /var/www/html/.htaccess

        # Update RewriteBase if FS_ROUTE is set
        if [ -n "${FS_ROUTE:-}" ]; then
            sed -i "s|RewriteBase /|RewriteBase ${FS_ROUTE}|g" /var/www/html/.htaccess
        fi

        chown nobody:nobody /var/www/html/.htaccess
        echo ".htaccess created successfully."
    else
        echo ".htaccess already exists or htaccess-sample not found."
    fi
}

configure_facturascripts() {
    local config_file="/var/www/html/MyFiles/config.php"

    # Only configure if database environment variables are set
    if [ -n "${DB_HOST:-}" ] && [ -n "${DB_NAME:-}" ] && [ -n "${DB_USER:-}" ] && [ -n "${DB_PASSWORD:-}" ]; then
        echo "Configuring FacturaScripts with complete settings..."

        # Determine database type specific settings
        local db_type="${DB_TYPE:-mysql}"
        local pgsql_ssl=""
        local pgsql_endpoint=""
        local mysql_charset=""
        local mysql_collate=""

        if [ "$db_type" = "postgresql" ]; then
            pgsql_ssl="define('FS_PGSQL_SSL', '${FS_PGSQL_SSL:-}');"
            pgsql_endpoint="define('FS_PGSQL_ENDPOINT', '${FS_PGSQL_ENDPOINT:-}');"
        else
            mysql_charset="define('FS_MYSQL_CHARSET', '${FS_MYSQL_CHARSET:-utf8mb4}');"
            mysql_collate="define('FS_MYSQL_COLLATE', '${FS_MYSQL_COLLATE:-utf8mb4_unicode_520_ci}');"
        fi

        # Create complete config.php with all necessary defines
        cat > "$config_file" <<EOF
<?php
// FacturaScripts Configuration - Auto-generated by Docker
define('FS_COOKIES_EXPIRE', ${FS_COOKIES_EXPIRE:-31536000});
define('FS_ROUTE', '${FS_ROUTE:-}');
define('FS_DB_TYPE', '${db_type}');
define('FS_DB_HOST', '${DB_HOST}');
define('FS_DB_PORT', '${DB_PORT:-3306}');
define('FS_DB_NAME', '${DB_NAME}');
define('FS_DB_USER', '${DB_USER}');
define('FS_DB_PASS', '${DB_PASSWORD}');
define('FS_DB_FOREIGN_KEYS', ${FS_DB_FOREIGN_KEYS:-true});
define('FS_DB_TYPE_CHECK', ${FS_DB_TYPE_CHECK:-true});
${mysql_charset}
${mysql_collate}
${pgsql_ssl}
${pgsql_endpoint}
define('FS_LANG', '${FS_LANG:-es_ES}');
define('FS_TIMEZONE', '${FS_TIMEZONE:-UTC}');
define('FS_HIDDEN_PLUGINS', '${FS_HIDDEN_PLUGINS:-}');
define('FS_DEBUG', ${FS_DEBUG:-false});
define('FS_DISABLE_ADD_PLUGINS', ${FS_DISABLE_ADD_PLUGINS:-false});
define('FS_DISABLE_RM_PLUGINS', ${FS_DISABLE_RM_PLUGINS:-false});
define('FS_DISABLE_RM_USERS', ${FS_DISABLE_RM_USERS:-false});
EOF

        # Add initial user credentials if provided
        if [ -n "${FS_INITIAL_USER:-}" ] && [ -n "${FS_INITIAL_PASS:-}" ]; then
            cat >> "$config_file" <<EOF
define('FS_INITIAL_USER', '${FS_INITIAL_USER}');
define('FS_INITIAL_PASS', '${FS_INITIAL_PASS}');
EOF
            echo "Initial user credentials configured: ${FS_INITIAL_USER}"
        fi

        chmod 600 "$config_file"
        chown nobody:nobody "$config_file"
        echo "FacturaScripts configuration completed."
        echo "Installation wizard will be skipped on first access."
    else
        echo "Database environment variables not set. Skipping automatic configuration."
        echo "Please configure FacturaScripts manually through the web interface."
    fi
}

# --- Main Execution ---

echo "=== FacturaScripts Entrypoint start ==="

# Wait for database if DB_HOST is set
[ -n "${DB_HOST:-}" ] && check_db_availability "$DB_HOST" "${DB_PORT:-3306}"

# Execute pre-configure commands if the variable is set
if [ -n "${PRE_CONFIGURE_COMMANDS:-}" ]; then
    echo "Executing pre-configure commands..."
    eval "$PRE_CONFIGURE_COMMANDS"
fi

# Create necessary folders
create_folders

# Configure .htaccess
configure_htaccess

# Configure FacturaScripts
configure_facturascripts

# Execute post-configure commands if the variable is set
if [ -n "${POST_CONFIGURE_COMMANDS:-}" ]; then
    echo "Executing post-configure commands..."
    eval "$POST_CONFIGURE_COMMANDS"
fi

echo "=== FacturaScripts Entrypoint completed ==="
exec "$@"
