#!/bin/sh
set -eu

# --- Functions ---

check_db_availability() {
    local db_host="$1"
    local db_port="$2"
    echo "Waiting for $db_host:$db_port to be ready..."
    while ! nc -w 1 "$db_host" "$db_port" >/dev/null 2>&1; do
        echo -n '.'
        sleep 1
    done
    echo "\nDatabase $db_host:$db_port is ready."
}

create_folders() {
    echo "Creating necessary folders..."

    # Create Dinamic folder if it doesn't exist
    [ ! -d "/var/www/html/Dinamic" ] && mkdir -p /var/www/html/Dinamic

    # Ensure MyFiles and Plugins folders exist
    [ ! -d "/var/www/html/volume/MyFiles" ] && mkdir -p /var/www/html/volume/MyFiles
    [ ! -d "/var/www/html/volume/Plugins" ] && mkdir -p /var/www/html/volume/Plugins

    # Set permissions
    chown -R nobody:nobody /var/www/html/Dinamic
    chown -R nobody:nobody /var/www/html/volume

    echo "Folders created successfully."
}

configure_htaccess() {
    echo "Configuring .htaccess..."

    if [ -f "/var/www/html/htaccess-sample" ] && [ ! -f "/var/www/html/.htaccess" ]; then
        cp /var/www/html/htaccess-sample /var/www/html/.htaccess

        # Update RewriteBase if FS_ROUTE is set
        if [ -n "${FS_ROUTE:-}" ]; then
            sed -i "s|RewriteBase /|RewriteBase ${FS_ROUTE}|g" /var/www/html/.htaccess
        fi

        chown nobody:nobody /var/www/html/.htaccess
        echo ".htaccess created successfully."
    else
        echo ".htaccess already exists or htaccess-sample not found."
    fi
}

configure_facturascripts() {
    local config_file="/var/www/html/config.php"

    # Only configure if database environment variables are set
    if [ -n "${DB_HOST:-}" ] && [ -n "${DB_NAME:-}" ] && [ -n "${DB_USER:-}" ] && [ -n "${DB_PASSWORD:-}" ]; then
        echo "Configuring FacturaScripts with complete settings..."

        # Determine database type specific settings
        local db_type="${DB_TYPE:-mysql}"
        local pgsql_ssl=""
        local pgsql_endpoint=""
        local mysql_charset=""
        local mysql_collate=""

        if [ "$db_type" = "postgresql" ]; then
            pgsql_ssl="define('FS_PGSQL_SSL', '${FS_PGSQL_SSL:-}');"
            pgsql_endpoint="define('FS_PGSQL_ENDPOINT', '${FS_PGSQL_ENDPOINT:-}');"
        else
            mysql_charset="define('FS_MYSQL_CHARSET', '${FS_MYSQL_CHARSET:-utf8mb4}');"
            mysql_collate="define('FS_MYSQL_COLLATE', '${FS_MYSQL_COLLATE:-utf8mb4_unicode_520_ci}');"
        fi

        # Create complete config.php with all necessary defines
        cat > "$config_file" <<EOF
<?php
// FacturaScripts Configuration - Auto-generated by Docker
define('FS_COOKIES_EXPIRE', ${FS_COOKIES_EXPIRE:-31536000});
define('FS_ROUTE', '${FS_ROUTE:-}');
define('FS_DB_TYPE', '${db_type}');
define('FS_DB_HOST', '${DB_HOST}');
define('FS_DB_PORT', '${DB_PORT:-3306}');
define('FS_DB_NAME', '${DB_NAME}');
define('FS_DB_USER', '${DB_USER}');
define('FS_DB_PASS', '${DB_PASSWORD}');
define('FS_DB_FOREIGN_KEYS', ${FS_DB_FOREIGN_KEYS:-true});
define('FS_DB_TYPE_CHECK', ${FS_DB_TYPE_CHECK:-true});
${mysql_charset}
${mysql_collate}
${pgsql_ssl}
${pgsql_endpoint}
define('FS_LANG', '${FS_LANG:-es_ES}');
define('FS_TIMEZONE', '${FS_TIMEZONE:-UTC}');
define('FS_HIDDEN_PLUGINS', '${FS_HIDDEN_PLUGINS:-}');
define('FS_DEBUG', ${FS_DEBUG:-false});
define('FS_DISABLE_ADD_PLUGINS', ${FS_DISABLE_ADD_PLUGINS:-false});
define('FS_DISABLE_RM_PLUGINS', ${FS_DISABLE_RM_PLUGINS:-false});
define('FS_DISABLE_RM_USERS', ${FS_DISABLE_RM_USERS:-false});
EOF

        # Add initial user credentials if provided
        if [ -n "${FS_INITIAL_USER:-}" ] && [ -n "${FS_INITIAL_PASS:-}" ]; then
            cat >> "$config_file" <<EOF
define('FS_INITIAL_USER', '${FS_INITIAL_USER}');
define('FS_INITIAL_PASS', '${FS_INITIAL_PASS}');
EOF
            echo "Initial user credentials configured: ${FS_INITIAL_USER}"
        fi

        chmod 600 "$config_file"
        chown nobody:nobody "$config_file"
        echo "FacturaScripts configuration completed."
        echo "Installation wizard will be skipped on first access."
    else
        echo "Database environment variables not set. Skipping automatic configuration."
        echo "Please configure FacturaScripts manually through the web interface."
    fi
}

install_plugins() {
    local marker_file="/var/www/html/Plugins/.plugins_installed"

    # Skip if plugins already installed
    if [ -f "$marker_file" ]; then
        echo "Plugins already installed (marker file exists). Skipping."
        return 0
    fi

    # Skip if no plugins defined
    if [ -z "${FS_PLUGINS:-}" ]; then
        echo "No plugins to install (FS_PLUGINS not set)."
        return 0
    fi

    # Skip if config.php doesn't exist (FacturaScripts not configured yet)
    if [ ! -f "/var/www/html/config.php" ]; then
        echo "FacturaScripts not configured yet. Skipping plugin installation."
        return 0
    fi

    echo "=== Installing FacturaScripts Plugins ==="

    # Common plugin name to ID mapping (for convenience)
    # Format: pluginname:downloadid
    local plugin_map="
        verifactu:448
        multiempresa:464
        webportal:460
        openpaypf:400
        notificaciones:356
        pagosonline:391
    "

    # Process each plugin
    local plugin_list=$(echo "$FS_PLUGINS" | tr '\n' ' ' | tr ',' ' ')
    local plugin_count=0
    local failed=0

    for plugin in $plugin_list; do
        # Skip empty entries
        [ -z "$plugin" ] && continue

        plugin_count=$((plugin_count + 1))
        echo ""
        echo "[$plugin_count] Processing plugin: $plugin"

        local download_url=""
        local plugin_file=""

        # Detect plugin type and get download URL
        if echo "$plugin" | grep -q '^https\?://'; then
            # Full URL
            download_url="$plugin"
            plugin_file="/tmp/plugin-$plugin_count.zip"
            echo "  Type: URL"
        elif echo "$plugin" | grep -q '^[0-9]\+$'; then
            # Numeric ID
            download_url="https://facturascripts.com/DownloadBuild/${plugin}/stable"
            plugin_file="/tmp/plugin-${plugin}.zip"
            echo "  Type: Download ID"
        else
            # Plugin name - try to find in mapping
            local mapped_id=$(echo "$plugin_map" | grep -i "^[[:space:]]*${plugin}:" | cut -d: -f2 | tr -d ' ')

            if [ -n "$mapped_id" ]; then
                download_url="https://facturascripts.com/DownloadBuild/${mapped_id}/stable"
                plugin_file="/tmp/plugin-${plugin}.zip"
                echo "  Type: Plugin name (mapped to ID: $mapped_id)"
            else
                echo "  ERROR: Unknown plugin name: $plugin"
                echo "  Available named plugins: verifactu, multiempresa, webportal, openpaypf, notificaciones, pagosonline"
                echo "  Tip: Use download ID or full URL instead"
                failed=1
                break
            fi
        fi

        echo "  Download URL: $download_url"
        echo "  Downloading..."

        # Download plugin
        if ! wget -q -O "$plugin_file" "$download_url"; then
            echo "  ERROR: Failed to download plugin from: $download_url"
            failed=1
            break
        fi

        # Verify it's a valid ZIP
        if ! unzip -t "$plugin_file" >/dev/null 2>&1; then
            echo "  ERROR: Downloaded file is not a valid ZIP"
            rm -f "$plugin_file"
            failed=1
            break
        fi

        echo "  Installing plugin..."

        # Install plugin using PHP script
        if ! php84 /usr/local/bin/install-facturascripts-plugin.php "$plugin_file"; then
            echo "  ERROR: Failed to install plugin"
            rm -f "$plugin_file"
            failed=1
            break
        fi

        # Clean up
        rm -f "$plugin_file"
        echo "  ✓ Plugin installed successfully"
    done

    if [ $failed -eq 1 ]; then
        echo ""
        echo "ERROR: Plugin installation failed. Container startup aborted."
        echo "Please check the errors above and fix your FS_PLUGINS configuration."
        exit 1
    fi

    if [ $plugin_count -eq 0 ]; then
        echo "No valid plugins found in FS_PLUGINS."
    else
        # Create marker file
        touch "$marker_file"
        chown nobody:nobody "$marker_file"
        echo ""
        echo "✓ All plugins installed successfully ($plugin_count plugins)"
    fi

    echo "=== Plugin Installation Completed ==="
}

rebuild_facturascripts() {
    local marker_file="/var/www/html/Dinamic/.rebuild_done"

    # Skip if already rebuilt
    if [ -f "$marker_file" ]; then
        echo "FacturaScripts already rebuilt (marker file exists). Skipping."
        return 0
    fi

    # Skip if config.php doesn't exist (FacturaScripts not configured yet)
    if [ ! -f "/var/www/html/config.php" ]; then
        echo "FacturaScripts not configured yet. Skipping rebuild."
        return 0
    fi

    echo "=== Rebuilding FacturaScripts ==="
    echo "This process generates Dinamic classes and may take a few seconds..."

    # Execute rebuild script
    if ! php84 /usr/local/bin/rebuild-facturascripts.php; then
        echo "ERROR: FacturaScripts rebuild failed."
        echo "The application may not work correctly until you manually rebuild it."
        echo "You can rebuild by accessing: http://your-site/deploy?action=rebuild"
        # Don't exit - let the container start so user can access the rebuild page
        return 1
    fi

    # Create marker file to prevent rebuilding on every restart
    touch "$marker_file"
    chown nobody:nobody "$marker_file"

    echo "✓ FacturaScripts rebuilt successfully"
    echo "=== Rebuild Completed ==="
}

# --- Main Execution ---

echo "=== FacturaScripts Entrypoint start ==="

# Wait for database if DB_HOST is set
[ -n "${DB_HOST:-}" ] && check_db_availability "$DB_HOST" "${DB_PORT:-3306}"

# Execute pre-configure commands if the variable is set
if [ -n "${PRE_CONFIGURE_COMMANDS:-}" ]; then
    echo "Executing pre-configure commands..."
    eval "$PRE_CONFIGURE_COMMANDS"
fi

# Create necessary folders
create_folders

# Configure .htaccess
configure_htaccess

# Configure FacturaScripts
configure_facturascripts

# Install plugins if configured
install_plugins

# Rebuild FacturaScripts after initial configuration
rebuild_facturascripts

# Execute post-configure commands if the variable is set
if [ -n "${POST_CONFIGURE_COMMANDS:-}" ]; then
    echo "Executing post-configure commands..."
    eval "$POST_CONFIGURE_COMMANDS"
fi

echo "=== FacturaScripts Entrypoint completed ==="
exec "$@"
